name: Builder

on:
  workflow_dispatch:
    inputs:
      build_version:
        description: 'Build version:'
        required: true      
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "beta" ]
  release:
    types: [published]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+(-rc)?"     
      
run-name: "${{ github.event.inputs.build_version || github.event.release.tag_name || github.event.inputs.commit_message }}"   
jobs:   

  trigger-ci:
    uses: my-prop-trading/DevOps/.github/workflows/cicd_builder.yml@main
    with:
      language: rust
      service_type: server
      #----------------------------------------------------------------
      repository_name: ${{ github.event.repository.name }}
      release_version: $(echo ${GITHUB_REF_NAME})
      image_name: myproptrading/${{ github.event.repository.name }}
      build_version: ${{ github.event.inputs.build_version }}
      
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      TELEGRAM_NOTIFICATION_TOKEN: ${{ secrets.TELEGRAM_NOTIFICATION_TOKEN }}
      TELEGRAM_GITHAB_CHAT_ID: ${{ secrets.TELEGRAM_GITHAB_CHAT_ID }}
      SSH_ACCESS_ALPHA_01: ${{ secrets.SSH_ACCESS_ALPHA_01 }}
      SSH_ACCESS_BETA_01: ${{ secrets.SSH_ACCESS_BETA_01 }}
      SSH_ACCESS_BETA_04: ${{ secrets.SSH_ACCESS_BETA_04 }}
      SSH_ACCESS_DEMO_01: ${{ secrets.SSH_ACCESS_DEMO_01 }}
      SSH_KEY_FOR_DEPLOY: ${{ secrets.SSH_KEY_FOR_DEPLOY }}
